### ISSUE TITLE
Todo website

### ISSUE THREAD

**Issue by sayanee** [hutscape/hutscape.github.io#1]
- [x] Add Google Analytics fe5e87c
- [x] Add icons for project properties 26ef043
- [x] Add `_includes` directory as a [git submodule in project repositories](https://github.com/hutscape/project-includes)
- [x] Add project details from `readme.md` into project data in project repositories
- [x] Amend and simplify `readme.md` for project repositories
- [ ] Create a static data file in this repository through scripting to pick up all the individual project properties from other repositories
